version: '2'
catalog:
  name: "Wordpress"
  version: "v0.1-myapp"
  description: "Just a test"
services:
  wordpress:
    scale: 1
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: wordpress
        source_port: 10080
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  mysql:
    scale: 1
    start_on_create: true
